Optimize parametrization
appuio/puppet-openshift pull request #2
Opened 2017-10-24 09:58 UTC by bliemli

2017-10-24 10:15 UTC, hansmi requested changes
The commit messages should start with a capitalized letter and contain a body (see, for example, https://chris.beams.io/posts/git-commit/).

2017-10-24 10:15 UTC, hansmi commented on manifests/role/ansible_master.pp
> +  $packages = [
Adding more packages requires duplicating the existing values, and list updates become more difficult. I presume you want to define a list on your own. You can do that by adding a new boolean parameter named like `$install_required_packages`. That way external code can install the desired packages.

2017-10-24 10:15 UTC, hansmi commented on manifests/role/ansible_master.pp
>    validate_hash($host_groups)
Missing `validate_absolute_path($ansible_inventory)` (feel free to add validations for the other parameters in a separate commit).

2017-10-30 09:31 UTC, bliemli commented
Just reviewed with Lorenz. We are closing this PR and will open a new one.

2017-10-30 09:31 UTC, bliemli commented
Just reviewed with Lorenz. We are closing this PR and will open a new one.

2017-10-30 09:31 UTC, closed without merging